/*
 * signal_generator microblx function block (autogenerated, don't edit)
 */

#include <ubx.h>

UBX_MODULE_LICENSE_SPDX(BSD-3-Clause)

/* includes types and type metadata */

ubx_type_t types[] = {
};

/* block meta information */
char signal_generator_meta[] =
	" { doc='',"
	"   realtime=true,"
	"}";

/* declaration of block configuration */
ubx_proto_config_t signal_generator_config[] = {
	{ .name="data_len", .type_name = "unsigned int", .min=0, .max=0, .doc="length of signal array (def: 1)" },
	{ 0 },
};

/* declaration port block ports */
ubx_proto_port_t signal_generator_ports[] = {
	{ .name="out", .out_type_name="double", .out_data_len=1, .doc="controller output"  },
	{ 0 },
};

/* declare a struct port_cache */
struct signal_generator_port_cache {
	ubx_port_t* out;
};

/* helper function to cache ports. call in init */
static void update_port_cache(ubx_block_t *b, struct signal_generator_port_cache *pc)
{
	pc->out = ubx_port_get(b, "out");
}

/* define safe accessors for the new types */


/* block operation forward declarations */
int signal_generator_init(ubx_block_t *b);
int signal_generator_start(ubx_block_t *b);
void signal_generator_stop(ubx_block_t *b);
void signal_generator_cleanup(ubx_block_t *b);
void signal_generator_step(ubx_block_t *b);

ubx_proto_block_t signal_generator_block = {
	.name = "signal_generator",
	.type = BLOCK_TYPE_COMPUTATION,
	.meta_data = signal_generator_meta,
	.configs = signal_generator_config,
	.ports = signal_generator_ports,

	/* ops */
	.init = signal_generator_init,
	.start = signal_generator_start,
	.stop = signal_generator_stop,
	.cleanup = signal_generator_cleanup,
	.step = signal_generator_step,
};


/* signal_generator module init and cleanup functions */
int signal_generator_mod_init(ubx_node_t* nd)
{
	ubx_log(UBX_LOGLEVEL_DEBUG, nd, "%s", __func__);

	for (unsigned int i=0; i<ARRAY_SIZE(types); i++) {
		if(ubx_type_register(nd, &types[i]) != 0)
			return -1;
	}

	if(ubx_block_register(nd, &signal_generator_block) != 0)
		return -1;

	return 0;
}

void signal_generator_mod_cleanup(ubx_node_t *nd)
{
	ubx_log(UBX_LOGLEVEL_DEBUG, nd, "%s", __func__);

	for (unsigned int i=0; i<ARRAY_SIZE(types); i++)
		ubx_type_unregister(nd, types[i].name);

	ubx_block_unregister(nd, "signal_generator");
}

/* declare module init and cleanup functions, so that the ubx core can
 * find these when the module is loaded/unloaded */
UBX_MODULE_INIT(signal_generator_mod_init)
UBX_MODULE_CLEANUP(signal_generator_mod_cleanup)
