/*
 * graphics_bridge microblx function block (autogenerated, don't edit)
 */

#include <ubx.h>

UBX_MODULE_LICENSE_SPDX(BSD 3-Clause)

/* includes types and type metadata */

ubx_type_t types[] = {
};

/* block meta information */
char graphics_bridge_meta[] =
	" { doc='',"
	"   realtime=true,"
	"}";

/* declaration of block configuration */
ubx_proto_config_t graphics_bridge_config[] = {
	{ .name="joint_state_size", .type_name = "int", .min=1, .max=0, .doc="number of degrees of freedom" },
	{ 0 },
};

/* declaration port block ports */
ubx_proto_port_t graphics_bridge_ports[] = {
	{ .name="q", .in_type_name="double", .in_data_len=1, .doc="joint status vector"  },
	{ 0 },
};

/* declare a struct port_cache */
struct graphics_bridge_port_cache {
	ubx_port_t* q;
};

/* helper function to cache ports. call in init */
static void update_port_cache(ubx_block_t *b, struct graphics_bridge_port_cache *pc)
{
	pc->q = ubx_port_get(b, "q");
}

/* define safe accessors for the new types */


/* block operation forward declarations */
int graphics_bridge_init(ubx_block_t *b);
int graphics_bridge_start(ubx_block_t *b);
void graphics_bridge_stop(ubx_block_t *b);
void graphics_bridge_cleanup(ubx_block_t *b);
void graphics_bridge_step(ubx_block_t *b);

ubx_proto_block_t graphics_bridge_block = {
	.name = "graphics_bridge",
	.meta_data = graphics_bridge_meta,
	.type = BLOCK_TYPE_COMPUTATION,
	.configs = graphics_bridge_config,
	.ports = graphics_bridge_ports,

	/* ops */
	.init = graphics_bridge_init,
	.start = graphics_bridge_start,
	.stop = graphics_bridge_stop,
	.cleanup = graphics_bridge_cleanup,
	.step = graphics_bridge_step,
};


/* graphics_bridge module init and cleanup functions */
int graphics_bridge_mod_init(ubx_node_t* nd)
{
	//ubx_log(UBX_LOGLEVEL_DEBUG, nd, "%s", __func__);

	for (unsigned int i=0; i<ARRAY_SIZE(types); i++) {
		if(ubx_type_register(nd, &types[i]) != 0)
			return -1;
	}

	if(ubx_block_register(nd, &graphics_bridge_block) != 0)
		return -1;

	return 0;
}

void graphics_bridge_mod_cleanup(ubx_node_t *nd)
{
	//ubx_log(UBX_LOGLEVEL_DEBUG, nd, "%s", __func__);

	for (unsigned int i=0; i<ARRAY_SIZE(types); i++)
		ubx_type_unregister(nd, types[i].name);

	ubx_block_unregister(nd, "graphics_bridge");
}

/* declare module init and cleanup functions, so that the ubx core can
 * find these when the module is loaded/unloaded */
UBX_MODULE_INIT(graphics_bridge_mod_init)
UBX_MODULE_CLEANUP(graphics_bridge_mod_cleanup)
